gratipay/models/_mixin_team.py, tests/py/test_close.py
=> Fix deadlock when trying to close an account

gratipay/models/participant.py, tests/py/test_close.py, www/%username/account/close.spt
Fixes https://app.getsentry.com/gratipay/gratipay-com/group/48598522/
=> Fix 500 when bank withdrawal fails during account closure

gratipay/models/account_elsewhere.py, gratipay/models/participant.py, tests/py/test_elsewhere.py
=> Don't reset goal when logging in

gratipay/models/participant.py
https://app.getsentry.com/gratipay/gratipay-com/group/49188739/
Caused by #3020.
=> Fix opt-out

scss/gratipay.scss
=> Fix style of search results

branch.sql, js/gratipay/account.js, templates/profile.html, tests/py/test_privacy_json.py, www/%username/account/index.html.spt, www/%username/index.html.spt, www/%username/privacy.json.spt, www/search.spt
This PR should add the is_searchable functionality, allowing users to control their privacy settings for our internal search and public search (Google, Yahoo, etc).
I also moved the metadata in the profile head that should be shared across all pages for that user.
=> Search Opt Out

js/gratipay/charts.js, scss/molecules/chart.scss, www/%username/receiving/index.html.spt, www/about/stats.spt
Fixes a bug and refactors a few things.
=> massage charts

www/about/security/index.spt
=> fix security email

branch.sql, gratipay/billing/payday.py
=> Fix `charge_volume`

gratipay/models/__init__.py
=> Fix DB check

gratipay/billing/payday.py
Surfaced in #3045 and again in #3088.
=> Fix detection of failed credit card holds

templates/your-tip.html
The sole concern I have here is with long usernames overflowing the the column. It flows to a second line if the name is up to ~20 chars, but will look ugly past that.
Fixes #3093.
=> Adds call to action with "Give to tippee" when tip == 0

gratipay/testing/__init__.py, gratipay/wireup.py
=> Clean up test artifacts

templates/your-tip.html
=> i18n Your Tip on profile page

www/%username/elsewhere/refresh.spt
We don't always have a user session available, and this isn't a high-traffic or public endpoint.
[IRC](https://botbot.me/freenode/gratipay/2015-01-13/?msg=29413325&page=1)
=> refresh using app session instead of user session

gratipay/models/_mixin_team.py, gratipay/models/participant.py, js/gratipay/account.js, tests/py/test_participant.py, www/%username/number.json.spt
=> Fix takes when changing to individual

gratipay/utils/fake_data.py
=> Fix fake data

Makefile, fake_payday.sql, release.sh, schema.sql
=> Check for schema drift during release

gratipay/testing/__init__.py, gratipay/wireup.py
=> Clean up assets before exiting

branch.sql, tests/py/test_communities_json.py
=> Automatically delete empty communities

README.md, branch.sql, gratipay/main.py, gratipay/models/participant.py, gratipay/security/authentication.py, gratipay/security/user.py, js/gratipay/account.js, scss/gratipay.scss, scss/pages/account.scss, scss/pages/profile-edit.scss, tests/py/test_hooks.py, tests/py/test_user.py, www/%username/account/index.html.spt
This PR changes the credentials we require for HTTP Basic auth. It also fixes https://app.getsentry.com/gratipay/gratipay-com/group/45029121/ and https://app.getsentry.com/gratipay/gratipay-com/group/45029122/
=> Fix basic auth

scss/components/cta.scss, templates/your-tip.html
=> Fix tip button

templates/sign-in-using-to-give.html, templates/your-tip.html, tests/py/test_elsewhere.py, tests/py/test_pages.py
I thought I made a ticket for this but I'm not finding it now. Buttons are frobulated on elsewheres:
=> Unfrobulate button

www/about/faq.spt, www/bank-account.html.spt
=> Added minimum payout to FAQ pages, fixes #2966

templates/participant.html, tests/py/test_pages.py, www/about/fraud/2012-11-05.spt
[IRC](https://botbot.me/freenode/gratipay/2015-02-13/?msg=31951157&page=1)
=> fix an overescaping bug

scss/elements/elements.scss, templates/community-listing.html, templates/profile-edit.html, templates/team-listing.html
A couple of commits rebased out of #2809.
=> Miscellaneous changes

templates/support-gratipay.html, tests/py/fixtures/TestPages.yml, tests/py/test_pages.py
On the fence meaning you're a user of the site but have neither set up a tip to Gratipay nor explicitly opted out (free rider). This regressed in #3181.
=> fix site for on-the-fence users

scss/components/table.scss, scss/layouts/layout.scss
Before: 
After:
Before: 
After:
=> Minor UI changes

gratipay/security/authentication.py, gratipay/security/user.py
Self-explanatory code cleanup.
=> Simplify the `User` class

gratipay/utils/username.py, tests/py/test_utils.py
=> Fix safely_reserve_a_username. fixes #2981

gratipay/models/participant.py, gratipay/utils/__init__.py, templates/profile-sidebar.html, www/%username/history/index.html.spt
=> Allow admins to browse archived and closed accounts

Makefile
Modifies `make py` to run the entire `main.py` instead of only wiring the DB.
=> Improve `make py`

error.spt, templates/account-row.html, templates/auth.html, templates/base.html, templates/profile-edit.html, templates/search-box.html, templates/venmo-account.html, www/%username/account/index.html.spt, www/%username/emails/verify.html.spt, www/%username/history/index.html.spt, www/%username/index.html.spt, www/for/%slug/index.html.spt, www/on/%platform/%user_name/failure.html.spt, www/on/%platform/%user_name/index.html.spt, www/search.spt
=> Prune explicit escaping now that autoescaping is on

tests/py/test_privacy_json.py, www/about/stats.spt, www/search.spt
=> Work around content negociation bug

gratipay/main.py, tests/py/test_hooks.py
=> Fix content negociation

scss/components/memberships.scss, scss/components/profile-statement.scss, scss/gratipay.scss, templates/profile-edit.html, www/%username/index.html.spt, www/search.spt
Fixes this regression from b03cb93b8c9f0602462d079db9e97176557f7413:
Also implements #3216.
=> Style fixes

js/gratipay.js, js/gratipay/account.js, js/gratipay/forms.js, js/gratipay/payments.js, js/gratipay/profile.js, js/gratipay/team.js, js/gratipay/tips.js, tests/py/test_anonymous_json.py, tests/py/test_membername_json.py, www/%username/anonymous.json.spt, www/%username/members/%membername.json.spt, www/%username/members/index.html.spt, www/%username/tip.json.spt, www/assets/admin.js, www/bank-account.html.spt, www/credit-card.html.spt, www/explore/index.html.spt
First step towards notifications that don't suck.
=> Notifications cleanup

gratipay/models/participant.py, tests/py/test_participant.py, www/%username/number.json.spt
=> Ask for confirmation when anonymous receiving participant changes to team

emails/base.spt, tests/py/test_email.py, tests/py/test_email_notifs.py, www/%username/account/index.html.spt
=> Add notification preferences link to notification emails

gratipay/main.py, gratipay/security/authentication.py, gratipay/security/csrf.py, gratipay/testing/__init__.py, gratipay/utils/__init__.py, tests/py/test_callbacks.py, tests/py/test_elsewhere.py, tests/py/test_hooks.py
Split from #3189, requires more work. If I'm reading it right it breaks the CSRF check, yet tests are green, that's a problem.
=> More idiomatic hooks

README.md
After getting the env set up again I wanted to take a look at clearing up some things in the README I ran into while building on OS X. Indirectly a part of #2927
=> Explain some edge cases in Dependencies

js/gratipay/payments.js
Looks like I broke the credit card and bank account pages in #3218 (5667f656cf4047dc9e70a53e12ca82a5a751a413).
=> Fix a reference error in `payments.js`

gratipay/utils/history.py, scss/pages/history.scss, sql/branch.sql, tests/py/test_history.py, tests/py/test_record_an_exchange.py, www/%username/history/index.html.spt, www/%username/history/record-an-exchange.spt
=> Split history page by year

www/about/security/hall-of-fame.spt
https://github.com/gratipay/security-f4b75c/issues/1
=> acknowledge security researcher

www/bank-account.html.spt
https://app.getsentry.com/gratipay/gratipay-com/group/58325984/
Regression from #3247, a4c436aa2d8d8615b97640a42acd39657c1316e8 in there was rebased out of #3250 but I forgot to adapt it.
=> Fix bank account page

gratipay/models/account_elsewhere.py, sql/branch.sql, sql/elsewhere_with_participant.sql, tests/py/test_elsewhere.py, www/on/%platform/associate.spt, www/on/confirm.html.spt, www/on/take-over.html.spt
=> Get rid of `website.connect_tokens`

gratipay/__init__.py, gratipay/main.py, gratipay/security/authentication.py, gratipay/security/csrf.py, gratipay/utils/cache_static.py, gratipay/utils/http_caching.py, gratipay/wireup.py, templates/base.html, tests/py/test_hooks.py
Fixes https://github.com/gratipay/gratipay.com/pull/3200#issuecomment-77206397 and other related issues.
=> Clean up HTTP headers

gratipay/main.py, gratipay/renderers/csv_dump.py, gratipay/utils/history.py, tests/py/test_history.py, www/%username/history/export.spt, www/%username/history/index.html.spt
=> History export

tests/py/fixtures/TestPages.yml, tests/py/test_bitcoin_json.py, tests/py/test_elsewhere.py, tests/py/test_goal_json.py, tests/py/test_pages.py, www/%username/bitcoin.json.spt, www/%username/delete-elsewhere.json.spt, www/%username/goal.json.spt, www/%username/privacy.json.spt, www/%username/receipts/%exchange_id.int.html.spt, www/%username/widget.html.spt, www/bank-account.json.spt, www/credit-card.json.spt, www/dashboard/index.spt, www/on/%platform/%user_name/failure.html.spt, www/on/%platform/associate.spt, www/ride-free.json.spt
https://github.com/gratipay/gratipay.com/pull/3250#issuecomment-81960973
=> Fix browse tests

.travis.yml
http://docs.travis-ci.com/user/workers/container-based-infrastructure/
=> Use container-based testing for Travis

scss/pages/cc-ba.scss
See https://github.com/gratipay/gratipay.com/pull/3250#issuecomment-82888647 and https://github.com/gratipay/gratipay.com/pull/3250#issuecomment-83131900. @whit537 merged the PR before I could put this in.
=> Grey tooltips

scss/components/nav.scss, scss/gratipay.scss, scss/layouts/layout.scss
The only commit I got in on #3258 before bailing back up.
=> factor out a nav component in scss

.travis.yml
=> Cache python dependencies across Travis builds

.travis.yml, Makefile
Commits from #3264 that are still useful. cc @techtonik
=> Env tweaks

www/about/security/hall-of-fame.spt
For https://github.com/gratipay/security-2a443f/issues/1.
=> acknowledge BALAJI

gratipay/models/participant.py
=> Fix usage of balanced.Card

scss/components/profile-statement.scss
=> constrain width on images in profile statements

www/%username/routes/bank-account.html.spt, www/%username/routes/credit-card.html.spt
Alternative to #3311. [IRC](https://botbot.me/freenode/gratipay/2015-04-02/?msg=35694755&page=1)
=> Re-inline the cc/ba number in the form

.travis.yml
Because https://github.com/gratipay/inside.gratipay.com/issues/149#issuecomment-78670585 et seq.
=> Stop using coveralls

gratipay/billing/exchanges.py, gratipay/models/exchange_route.py, tests/py/test_billing_exchanges.py, tests/py/test_routes.py
For https://github.com/gratipay/gratipay.com/issues/2779#issuecomment-89053807 etc.
=> Fix handling of exchange routes

scss/components/sign_in.scss, tests/py/test_pages.py, www/%username/routes/bank-account.html.spt, www/%username/routes/credit-card.html.spt
This is to fix issue of #3310. Please review @whit537.
=> Added title to the bank account page for anon

gratipay/models/participant.py, tests/py/test_email.py
=> silently skip emails when we don't have an address

gratipay/utils/history.py, tests/py/test_history.py
https://github.com/gratipay/gratipay.com/issues/3336
=> Let admins view history of closed accounts

Makefile
Fixes #3300.
I really don't know how this works or if this is indeed the right way, just blindly followed https://github.com/gratipay/gratipay.com/issues/3300#issuecomment-87796314
=> stop make run from rebuilding env

data/routing.txt
This creates a basis for solving #3326. Please add more info.
=> The ultimate transparency is here. Yay! =)

js/gratipay/giving.js, scss/pages/giving.scss, templates/giving-table.html, tests/py/test_pages.py, www/%username/giving/index.html.spt
This is cleanup before fixing #3107.
=> Improve giving page - part 1

gratipay/billing/exchanges.py, tests/py/test_billing_exchanges.py
=> Fix amount failed charges

scss/elements/elements.scss, www/about/faq.spt
Fixes #3333. Please review @techtonik, @whit537, @rohitpaulk   or anyone else.
=> Added anchors for FAQ question headers.

www/%username/giving/index.html.spt
=> Fix order of tabs on giving page

README.md, Vagrantfile, scripts/vagrant-debian.sh, scripts/vagrant-setup.sh
This updates README.md, removes some warning and fills in missing dependencies
=> Polishing Vagrant workflow

templates/avatar-url.html
Reverts gratipay/gratipay.com#3383.
=> Revert "Avoid blurry images and be retina ready"

sql/branch.sql
Part of #3399. cc: @rohitpaulk.
=> here's the new teams table

www/~/%username/routes/associate.json.spt
=> Display braintree errors properly

gratipay/models/participant.py
Simple shuffling, no code changes
=> Reorganize methods in participant model

www/about/faq.spt
Per discussion here: https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-102085739
=> Removed mention of Bitcoin.

sql/branch.sql
=> constraint payments.schema > 0 in the schema

gratipay/billing/exchanges.py
Suggested by @rohitpaulk somewhere, can't find where. :)
Relates to #3415.
=> log hold cancellations

tests/py/test_billing_payday.py
https://github.com/gratipay/gratipay.com/pull/3437#issuecomment-102464406
=> revive tests for xx_payments.csv helper

gratipay/billing/payday.py, sql/payday.sql
=> improves debugging

gratipay/billing/exchanges.py, gratipay/billing/payday.py, tests/py/test_billing_payday.py
=> Log during fetch_card_holds

gratipay/billing/payday.py
=> Add a couple more log lines

gratipay/models/participant.py, tests/py/test_close.py, tests/py/test_history.py, www/~/%username/settings/close.spt
https://github.com/gratipay/gratipay.com/issues/3453#issuecomment-103073394
https://github.com/gratipay/gratipay.com/pull/3392#issuecomment-100435765
=> close the close loophole for payouts

gratipay/models/participant.py, tests/py/test_is_approved.py, www/%team/toggle-is-approved.json.spt, www/dashboard/teams.spt, www/new.spt
@rohitpaulk after #3412 is ready for review, you can rebase this on that and start implementing a review dashboard for teams. It can be basically the same as the fraud review dashboard. It's admin-only so it can be ugly. :)
=> Teams dashboard

js/gratipay/payments.js
=> Fix deleting routes

.gitignore, gratipay/models/exchange_route.py, gratipay/models/participant.py, js/gratipay/payments.js, tests/py/test_routes.py, www/~/%username/routes/associate.json.spt, www/~/%username/routes/paypal.html.spt, www/~/%username/settings/index.html.spt
=> Add paypal config to UI

gratipay/models/participant.py, gratipay/models/team.py, gratipay/utils/__init__.py, templates/team-listing.html, templates/team.html, tests/py/test_pages.py, tests/py/test_participant.py, tests/py/test_teams.py, tests/py/test_utils.py, www/%team/index.html.spt
First attempts at creating the Team profile page. Incomplete and not sure it is the direction required.
=> Create Team profile page

gratipay/models/team.py, tests/py/test_privacy_json.py, tests/py/test_teams.py, www/explore/teams/index.spt
=> switch Explore > Teams to new teams

www/%team/index.html.spt
=> fix link to team homepage

templates/base.html
We can be a little more optimistic now that Gratipay 2.0 is out the door.
=> update transition message

tests/py/test_teams.py, www/teams/create.json.spt
Here is my attempt to resolve #3479 ping @rohitpaulk, @whit537
=> Strip required input for new team form

js/gratipay/routes.js
Regression introduced in f526d9613354abc77044d5fdac8c2beceb7dc887 (#3467).
=> fix the URL for Balanced js

gratipay/models/team.py, tests/py/test_teams.py
https://github.com/gratipay/gratipay.com/issues/3486#issuecomment-106638547
=> Ignore new subscriptions in Team#migrate_tips

npm-shrinkwrap.json, package.json
This fixes #3000. All other jstests issues are not Vagrant/VirtualBox specific.
=> Upgrade grunt-webdriver 0.5.1 -> 0.5.2 for jstest

bin/masspay.py
I guess this is pending? We'll have to check again later ...
=> Our first "Unclaimed" PayPal payout

emails/charge_failed.spt, emails/charge_succeeded.spt, gratipay/billing/payday.py, sql/payday.sql, tests/py/test_billing_payday.py
=> Fix payday emails

www/~/%username/routes/delete.json.spt
Fixes https://app.getsentry.com/gratipay/gratipay-com/group/68712654/ and https://app.getsentry.com/gratipay/gratipay-com/group/68712262/. 
Which are likely to be caused by https://github.com/gratipay/gratipay.com/issues/3540#issuecomment-111305665
=> Add a few extra checks to routes/delete.json

bin/masspay.py
Introduced in d58af0b73b61fc23aa3730489bf34c4209d06b88
=> Fix a MassPay regression

gratipay/wireup.py
Fixes a regression from #3588.
=> Fix compile_assets for base_url

www/on/%platform/redirect.spt
=> Fix sign in

gratipay/billing/payday.py
We only support PayPal now, which we process in a separate step from payday proper.
=> remove payout from payday

gratipay/models/participant.py, gratipay/utils/notifications.py, sql/branch.sql
=> Fix bank error notif

www/new.spt
=> be up front that team applications are public

www/~/%username/old-balance-status.spt
Regression from https://github.com/gratipay/gratipay.com/pull/3588.
=> Fix bug in payout status button redirect

www/new.spt
Based on applications that have come in, I think this is the more essential question we should be asking.
=> Tweak revenue prompt

bin/masspay.py, tests/py/test_history.py
Changes to address issue:
stop holding balance to cover next week's payments #3475
=> Stop holding balance to cover next week's payments

www/about/pricing.spt
Per https://github.com/gratipay/gratipay.com/issues/3628#issuecomment-123843719.
=> Unlink "people" from Pricing page

js/gratipay.js
https://hackerone.com/reports/76307
=> Mitigate self-XSS

www/about/security/hall-of-fame.spt
This is for https://github.com/gratipay/security-flh0cu/issues/1.
=> ack security researcher

gratipay/main.py, gratipay/security/__init__.py, tests/py/test_pages.py
Ping @rohitpaulk @rorepo @kzisme @techtonik et al.
=> here's a couple best-practice security headers

www/about/faq.spt
No more direct deposits, only PayPal.  https://github.com/gratipay/gratipay.com/issues/3645
=> Update payout/withdrawal options

www/~/%username/settings/index.html.spt
https://github.com/gratipay/gratipay.com/issues/3640
=> Remove UI for individual vs team

bin/migrate-tips.py, gratipay/models/team.py, tests/py/test_teams.py
To aid in debugging https://github.com/gratipay/gratipay.com/issues/3609.
=> report ntips from migrate_tips

templates/base.html, www/index.html.spt
=> fix giving in another place in the UI

www/~/%username/subscriptions/index.spt
Fixes https://github.com/gratipay/gratipay.com/commit/1fd8f38895f490188a9fb7ed07fcbf670115defb#commitcomment-12466562.
=> Fix giving redirect

tests/py/test_pages.py, www/about/entities.svg, www/about/index.spt
=> update "About > Overview" for 2.0

www/about/pricing.spt
This fixes the 500 (#3674), but not the cached values (#3599).
=> partially fix Pricing page

www/about/features/index.spt, www/about/features/payments.spt, www/about/features/payroll.spt
This is more parallel to pay-what-you-want.
=> it's really take-what-you-*want*

gratipay/testing/__init__.py, tests/py/test_billing_payday.py, tests/py/test_history.py, tests/py/test_pages.py, tests/py/test_participant.py, tests/py/test_payment_instruction_json.py, tests/py/test_teams.py, tests/py/test_utils.py, www/about/entities.svg, www/about/index.spt
Instead of The A-Team, where the single female character "[was written out of the show](https://en.wikipedia.org/wiki/The_A-Team#Sexism) at the start of the third season when the network determined that a female cast member was not necessary."
=> Use The Enterprise as our example Team

tests/py/test_members_json.py
=> more Enterprise

www/search.spt
=> remove communities from search

www/new.spt
Closes #3677 and https://github.com/gratipay/inside.gratipay.com/issues/311.
=> link to Review Teams howto from Team application

www/teams/create.json.spt
=> remove noop

error.spt
=> Don't require _ in error.spt

scss/components/banner.scss
=> tighten up details box

www/new.spt
- suppress sidebar
- add banner h1
- revise "Migration" paragraph
=> preen Team application

templates/profile.html, www/%team/index.html.spt
Now it's readable as "weekly giving," etc.
=> tinker with labels on detail tables

gratipay/billing/payday.py, gratipay/utils/__init__.py, gratipay/utils/fake_data.py, sql/branch.sql, sql/update-payday-numbers.sql, tests/py/test_pages.py, tests/py/test_paydays_json.py, www/about/charts.json.spt, www/about/paydays.json.spt, www/about/stats.spt
=> tweak stats

gratipay/utils/markdown.py, tests/py/test_utils.py
Gonna do a quick PR and merge/deploy on this one. H1 link to follow ...
=> protect against XSS in markdown content

tests/py/test_set_status_json.py, www/%team/set-status.json.spt
=> add back missing set-json files

sql/schema.sql, tests/py/test_teams.py
Follow-on from #3568 and #3744.
=> clean up master

www/%team/index.html.spt
=> pick off a few more emoji

gratipay/billing/exchanges.py
Ping @rohitpaulk @rorepo @yifeiwu et al. :-)
=> teach masspay.py about the schema changes in #3760

www/dashboard/index.spt
See https://github.com/gratipay/inside.gratipay.com/issues/344#issuecomment-141263031.
=> update user review dashboard for Braintree

gratipay/utils/__init__.py, templates/profile.html, tests/py/test_privacy_json.py
https://github.com/gratipay/gratipay.com/issues/3783
Someone else should check this locally because I can't right now.
=> Add user.participant to who can see giving numbers

Makefile
=> push test-schema dependency down

bin/masspay.py, gratipay/billing/exchanges.py, tests/py/test_billing_exchanges.py, tests/py/test_record_an_exchange.py, www/~/%username/history/record-an-exchange.spt
=> Add route to record exchange spt

gratipay/billing/exchanges.py, gratipay/billing/payday.py, gratipay/models/participant.py, sql/branch.py, tests/py/test_billing_exchanges.py, tests/py/test_billing_payday.py, tests/py/test_participant.py, tests/py/test_payment_instruction_json.py
Also fixes https://github.com/gratipay/gratipay.com/issues/3811
=> Cleanup billing code

gratipay/models/participant.py, tests/py/test_participant.py
=> Fix credit card expiry notification

gratipay/models/participant.py, templates/base.html, templates/giving-table.html, www/about/features/payments.spt, www/~/%username/giving/index.html.spt
https://github.com/gratipay/gratipay.com/issues/3779
=> Expose dues in UI for ~users

gratipay/models/account_elsewhere.py, gratipay/models/participant.py, gratipay/utils/fake_data.py, sql/branch.sql, tests/py/test_close.py, tests/py/test_membername_json.py, tests/py/test_participant.py, tests/py/test_public_json.py, www/on/%platform/%user_name/index.html.spt
https://github.com/gratipay/gratipay.com/issues/3648
=> Remove number from participant

Makefile, requirements.txt, requirements_tests.txt
https://github.com/gratipay/gratipay.com/issues/3260
=> Use local pip packages on heroku

gratipay/models/team.py, sql/branch.py, tests/py/test_participant.py
https://github.com/gratipay/gratipay.com/issues/3811#issuecomment-147529226
=> Fix usage of db/cursor in team.update_receiving

sql/branch.sql
Transferwise is needed for https://github.com/gratipay/gratipay.com/issues/3828.
Both are needed for https://github.com/gratipay/gratipay.com/issues/2779.
=> Add a couple additional payment networks

www/about/features/payments.spt, www/~/%username/routes/credit-card.spt
=> updated copy re: arrears

templates/base.html, www/1.0-payout.spt
To complement https://medium.com/gratipay-blog/39c07bd031b.
=> enable 1.0 payouts indefinitely

www/~/%username/giving/index.html.spt
https://github.com/gratipay/gratipay.com/issues/3833
=> Use array to preserve tab order on ~user giving page

gratipay/billing/payday.py, sql/branch.py, tests/py/test_billing_payday.py
https://github.com/gratipay/gratipay.com/issues/3847 and https://github.com/gratipay/gratipay.com/issues/3841
=> Fix payday stats

sql/branch.sql
This will let us start doing manual transfers with Dwolla, as a step towards #726.
=> add Dwolla as a payment network

release.sh
Hit this in releasing #3861 ... our first release in over a month!
=> adapt to a minor Heroku CLI change

gratipay/models/team.py, www/%team/public.json.spt
=> Add public API endpoint for teams

scss/components/chart.scss, www/about/stats.spt
Closes https://github.com/gratipay/gratipay.com/issues/3890.
=> Add notes on Gratipocalypse

README.md
Reticketed from https://github.com/gratipay/gratipay.com/pull/3909#issuecomment-182063339.
cc: @aandis
=> tweak URL for payment-instructions.json in README

README.md
=> Fix bootstrap-debian.sh name

www/%team/index.html.spt
@mattbk go ahead and merge if this looks good. :)
=> Added owned by on team page for admins. Fixes #3945.

www/dashboard/1.0-payouts.spt
Noticed this during gratipay/inside.gratipay.com#555.
=> Fix link in 1.0 review dashboard

tests/js/test_homepage.js, tests/js/test_verify_email.js, tests/js/utils/auth-helper.py, www/~/%username/emails/verify.html.spt
https://github.com/gratipay/gratipay.com/issues/3982
=> Fix resend verification email button

www/dashboard/index.spt
cf. #3974 
Ping @mattbk @rohitpaulk @aandis
=> fix dashboard link

gratipay/models/participant/mixins/identity.py, tests/py/test_participant_identities.py
=> implement clearing identities

gratipay/models/participant/mixins/identity.py, sql/branch.sql, tests/py/test_participant_identities.py
=> implement has_verified_identity

www/~/%username/identities/%country.spt, www/~/%username/identities/index.spt
- fix `code2` &rarr; `code` on listing
- don't require address 2
=> Tweak the identities UI

templates/profile.html
I grepped and didn't find any others.
=> Whack another code2 mole

www/about/features/payments.spt
Closes https://github.com/gratipay/gratipay.com/issues/4022.
=> Add details to about/features/payments.

README.md, scripts/bootstrap-debian.sh
=> Update dependency docs in light of #3998

.travis.yml
This is helpful for understanding how Travis is interacting with commits pushed to a PR.
=> Echo the current branch in Travis

gratipay/__init__.py
Closes https://github.com/gratipay/gratipay.com/issues/4052.
=> fix build on Read the Docs

README.md
Ready for review @clone1018 @mattbk et al.
=> Tighten up doc pointers in README

gratipay/testing/__init__.py, tests/py/fixtures/TestPages.yml, tests/py/test_pages.py, tests/py/test_teams.py, www/dashboard/reconciliation.spt
Crept in in 8313ca6089703ac2bc4db0ee898a425ffc50191b (#3363).
=> Fix bug in test_pages where we ignored many pages

tests/py/test_pages.py, tests/py/test_teams.py
=> extend test coverage a bit

scss/components/profile-statement.scss
cf. https://gratipay.com/~nashe/
=> Avoid some unicode weirdnesses on the statement

tests/py/test_billing_exchanges.py, tests/py/test_billing_payday.py, tests/py/test_charts_json.py, tests/py/test_close.py, tests/py/test_communities_json.py, tests/py/test_elsewhere.py, tests/py/test_email.py, tests/py/test_history.py, tests/py/test_identity_pages.py, tests/py/test_is_suspicious.py, tests/py/test_membername_json.py, tests/py/test_participant.py, tests/py/test_participant_identities.py, tests/py/test_payment_instruction_json.py, tests/py/test_payout_status.py, tests/py/test_public_json.py, tests/py/test_record_an_exchange.py, tests/py/test_ride_free_json.py, tests/py/test_routes.py, tests/py/test_set_status_json.py, tests/py/test_stats.py, tests/py/test_team_edit.py, tests/py/test_team_takes.py, tests/py/test_teams.py, tests/py/test_utils.py
=> *use* the new test helpers

gratipay/utils/fake_data.py, tests/py/test_fake_data.py
Was updating my local repo and realized that http://localhost:8537/about/pricing was not working because it expected a Gratipay team to exist in fake_data. 
Only needed minor changes.
=> Added Gratipay team to fakedata so pricing page will work

www/search.spt
This aims to fix [H1-154921](https://hackerone.com/reports/154921).
=> Prefix the search term to mitigate text injection

templates/team-base.html, www/%team/index.html.spt
=> Make the "Set Status" button work on subpages

tests/ttw/test_team_distributing.py
E.g.: https://travis-ci.org/gratipay/gratipay.com/builds/155108726
=> Squish an intermittent bug in ttw testing

gratipay/testing/browser.py
This saves time when running a subset of tests that don't require a browser.
=> Only start a browser if we have to

tests/ttw/test_team_distributing.py
=> Tweak timing for Travis

templates/base.html, www/index.html.spt
I've found myself on a few recent PRs implementing this, and then losing it when I abandon the PR and move on to another. Here's a simple PR we can hopefully merge sooner rather than later and use in the flurry of work about to hit underneath #4148.
=> Make it easier to tag pages for special CSS

gratipay/package_managers/readmes.py
Really this should be in envvar or CLI arg. Cuttin' corners.
=> Drop threads down to limit memory consumption

bin/verify-identity.py
Builds on https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-243819578. I used this script successfully under https://github.com/gratipay/inside.gratipay.com/issues/866.
=> Verify identity script

www/~/%username/widgets/index.html.spt
Just noticed there are many test failures:
5 failed, 677 passed, 36 xfailed, 17 error
Is there something wrong with my local settings? Or they are just broken?
=> #3924 remove inapplicable badges; adjust title

gratipay/package_managers/readmes.py
https://github.com/gratipay/gratipay.com/issues/4148#issuecomment-259328722
=> Optimize readme processing

gratipay/package_managers/readmes.py, package.json
Trying to work around Heroku cache issue: https://github.com/gratipay/gratipay.com/issues/4148#issuecomment-259527383.
=> Pin marky-markdown version

gratipay/sync_npm/fetch_readmes.py, tests/py/test_sync_npm.py
See https://github.com/gratipay/gratipay.com/issues/4148#issuecomment-259618363.
=> Delete 404 (unpublished) packages

gratipay/sync_npm/fetch_readmes.py, tests/py/test_sync_npm.py
=> Fix bugs in fetch_readmes

gratipay/sync_npm/fetch_readmes.py
Should fix https://sentry.io/gratipay/gratipay-com/issues/179441800/. Part of #4148.
=> Ignore connection errors when fetching packages

templates/profile.html, www/~/%username/widgets/index.html.spt
Also add a link to widget docs. Closes #3924.
=> Re-add link to ~user widgets

gratipay/utils/__init__.py, tests/py/test_email.py, tests/py/test_identity_pages.py, tests/py/test_statement_json.py, tests/py/test_username_json.py
Closes #4040 and probably replaces https://github.com/gratipay/gratipay.com/pull/4189. Not sure if it covers all of #4196.
=> Change 403 to 401.

tests/py/test_www_team_receiving.py, www/%team/receiving/index.html.spt
https://sentry.io/gratipay/gratipay-com/issues/122185928/
=> Fix receiving page for anonymous users

gratipay/utils/fake_data.py, tests/py/test_fake_data.py, tests/py/test_stats.py
Redid `fake_data.py` mainly so that I can finish #4128 but I think that it badly needed an update to catch up with the changes in direction that we have taken. 
So here is what I have done. So please review @aandis , @rohitpaulk , @whit537  and let me know if there are any problems/changes to be made. 
No rush since we may have more important things on the table.
=> Fixing fakedata

bin/verify-identity.py
=> Remove comma from docstring

CONTRIBUTING.md
Harmonized sentence endings.
And corrected a link.
As part of https://24pullrequests.com/
=> Markdownified the file

emails/team-approved.spt, emails/team-rejected.spt, templates/giving-table.html, templates/team-listing.html, www/%team/edit/edit.json.spt, www/%team/edit/index.html.spt, www/%team/index.html.spt
=> Replace missed instances of "team" with "project"

templates/base.html
=> Add lang attribute to the html start tag.

www/apply.spt
Noticed this while trying to apply for a new team
=> Review Projects not Teams!

gratipay/security/__init__.py, tests/py/test_security.py
Follow-on from #4250 ... here's one more, @EdOverflow.
(Rolled back again in Heroku.)
=> Fix CSP again

templates/base.html
Solves the following issue: https://hackerone.com/reports/176390
=> Add meta referrer tag

scss/layouts/responsiveness.scss, templates/base.html
https://github.com/gratipay/inside.gratipay.com/issues/959
=> add github ribbon on the homepage

backup.sh, bin/sync-npm.sh, deploy.sh, payday.sh, recreate-schema.sh, scripts/bootstrap-debian.sh
Use shellcheck - https://github.com/koalaman/shellcheck for shellscript static analyse, and then improve the codes for a better style and safer way, will try to send another PR to integrate with CI later.
=> Shellcheck - shellscript syntax improvement

gratipay/models/participant/__init__.py, tests/py/test_close.py
Part of #3602, should've happened in #4287.
=> Fix bug with closing account w/ closed project

scss/components/banner.scss, scss/layouts/responsiveness.scss, www/on/npm/%package/index.html.spt
This shuffles the elements around on the npm package page to make room for the workflow defined on https://github.com/gratipay/gratipay.com/issues/4297.
=> Make room for package claiming workflow

README.md
http://gratipay.slackarchive.io/gratipay/-/1485982662.004198/1486046585.004302/1486046511004297/
=> data->fake

tests/ttw/test_homepage.py, www/index.html.spt
=> Nix the welcome popup

gratipay/models/participant/__init__.py, gratipay/models/participant/identity.py, gratipay/models/participant/mixins/__init__.py, gratipay/models/team/__init__.py, gratipay/models/team/available.py, gratipay/models/team/closing.py, gratipay/models/team/membership.py, gratipay/models/team/mixins/__init__.py, gratipay/models/team/takes.py, gratipay/models/team/tip_migration.py, gratipay/wireup.py, tests/py/test_participant_identities.py, tests/py/test_security.py, tests/py/test_team_membership.py, tests/py/test_team_takes.py, tests/py/test_tip_migration.py, www/%team/distributing/%to.json.spt
=> Refactor mixins

gratipay/models/exchange_route.py, gratipay/testing/harness.py, sql/branch.sql, tests/py/test_billing_exchanges.py, tests/py/test_participant.py, tests/py/test_routes.py, www/~/%username/routes/associate.json.spt
=> Fix bug on disconnecting PayPal

js/gratipay/payments.js, templates/support-gratipay.html, tests/py/test_pages.py, tests/py/test_payment_instruction_json.py, tests/py/test_support_gratipay.py
=> Fix bug in CTA amounts under certain langs

README.md
=> Update git clone info in documentation

templates/project-listing.html
Forgot to push this commit before we merged https://github.com/gratipay/gratipay.com/pull/4353.
=> Remove errant class

tests/py/test_email.py, www/~/%username/emails/modify.json.spt
https://hackerone.com/reports/127995
=> Limit email address length

gratipay/utils/http_caching.py, tests/py/test_acme_challenge.py, tests/py/test_hooks.py
Developing a fix for a HackerOne ticket [#185833](https://hackerone.com/reports/185833) dealing with Incomplete or No Cache-control and Pragma HTTP Header Set! :sparkles:
=> Missing cache headers fix

tests/py/test_email.py, www/~/%username/emails/modify.json.spt
https://sentry.io/gratipay/gratipay-com/issues/236526695/
=> Convert Throttle to a 400

gratipay/application.py
=> Fix maxconn bug

gratipay/security/__init__.py, scss/components/github-ribbon.scss, templates/base.html, tests/py/test_security.py, www/assets/gratipay.css.spt
Closes #4322 ~~and~~ ... but not #4359. :-/
=> Fix bugs in CSP implementation

www/index.html.spt
Removes project count entirely per https://github.com/gratipay/gratipay.com/issues/4315
=> Remove count of projects in each category

gratipay/application.py, gratipay/models/package/__init__.py, gratipay/models/team/closing.py, tests/py/test_packages.py
Part of #4305, follows on #4404.
=> Unclaim package (close project)

emails/suspicious-false.spt, emails/suspicious-true.spt, tests/py/test_is_suspicious.py, www/~/%username/toggle-is-suspicious.json.spt
=> Suspicious email cleanups

.travis.yml
=> Unfrobulate Travis

gratipay/email.py, sql/branch.sql, tests/py/test_email.py
Root cause fix for https://github.com/gratipay/gratipay.com/issues/4393.
=> Mark dead letters dead and skip them

gratipay/testing/browser.py, tests/ttw/test_package_claiming.py
Part of #4305, follows on #4411.
=> Integration test: claim, approve, and give

Makefile, recreate-schema.sh
=> Fix schema-diff

README.md
=> Add instruction on how to exit virtualenv.

gratipay/wireup.py
=> Fix regression in envvar checks

templates/list-participants.html
=> Fix search css regression

gratipay/models/team/__init__.py, gratipay/models/team/review_status.py, gratipay/testing/harness.py, templates/project-listing.html, tests/py/test_search.py, www/%team/set-status.json.spt, www/search.spt
=> Add packages to search results for projects

gratipay/fake_data.py
This speeds up fake data a bit, and extracts a few functions out to improve readability
=> Improve fake data performance

gratipay/utils/__init__.py, tests/py/test_teams.py, tests/py/test_utils.py, www/index.html.spt
https://github.com/gratipay/gratipay.com/issues/4313#issuecomment-301209391
Partly solves #4313, minus the AJAXness
=> Homepage server tabs

gratipay/sync_npm.py, tests/py/test_sync_npm.py
=> Ignore deleted events for inexistent packages

gratipay/fake_data.py, tests/py/test_fake_data.py
Redux of #4433 that doesn't aim for inclusion in #4305, but rather blocks on #4305.
=> Make fake packages

gratipay/models/participant/__init__.py, gratipay/testing/harness.py, tests/py/test_search.py, tests/py/test_team_takes.py, tests/ttw/test_package_claiming.py
Fix for https://github.com/gratipay/gratipay.com/issues/4479.
=> Allow team owners to merge accounts

401.spt, scss/components/text-treatments.scss, scss/elements/buttons-knobs.scss, scss/pages/package.scss, tests/py/test_pages.py, www/dashboard/index.spt, www/on/npm/%package/index.html.spt
=> Make the 401 page friendlier

sql/branch.sql, tests/py/test_email.py
=> Add ctime to email queue table

README.md
Closes https://github.com/gratipay/gratipay.com/issues/4503.
=> Remove reference to stats.json, which doesn't exist.

www/dashboard/1.0-payouts.spt, www/dashboard/index.spt
https://sentry.io/gratipay/gratipay-com/issues/282026999/
=> Fix dashboard regressions from #4457

www/~/%username/toggle-is-suspicious.json.spt
=> Don't send an email when initially setting is_suspicious to false

scss/elements/elements.scss
Per https://twitter.com/alejandrogonzo/status/894742963430899712 ...
=> Make the global background color explicit

recreate-schema.sh
Took me a little longer to understand that this was happening while reviewing #4546. Should be an easy one here, @rohitpaulk.
=> Log payday.sql during recreate-schema.sh

www/security.txt
Security.txt is a standard that allows websites to define security policies. This standard sets clear guidelines for security researchers for how to report security issues and allows bug bounty programs to define a scope. Security.txt is the equivalent of robots.txt, but for security issues.
Link to project: https://github.com/EdOverflow/security-txt
=> Create a security txt.

www/security.spt
As requested per: https://github.com/gratipay/gratipay.com/pull/4568#issuecomment-322144688
=> Remove security.spt.

gratipay/sync_npm.py, tests/py/test_sync_npm.py
This is a PR for issue #4506. Please let me know if this is what you had in mind.
=> Handles missing doc in npm change stream

gratipay/security/__init__.py, gratipay/website.py, tests/py/test_security.py, tests/ttw/test_security_ttw.py, www/on/npm/%package.spt
Can lead to reflected XSS: https://hackerone.com/reports/262852.
=> Protect against null bytes in URI

deploy.sh
=> Fix syntax error in updated deploy.sh

www/index.spt
Ping @mattbk @kaguillera for merge. :o)
=> Link to blog post justifying recommendation

gratipay/homepage.py, tests/py/fixtures/PartialPost.yml, tests/py/test_www_homepage.py, tests/ttw/test_homepage.py
=> New homepage error handling

js/gratipay/homepage.js, scss/pages/homepage.scss, www/index.spt
Small follow-on to #4598 to provide some more context. Basic FAQ.
cc: @mattbk @kaguillera et al.
=> Add some explanatory text

COPYING
https://github.com/gratipay/inside.gratipay.com/issues/1161
=> Relicense as MIT

js/gratipay/homepage.js, js/gratipay/notification.js, scss/pages/homepage.scss, templates/base.html, tests/ttw/test_homepage.py, www/index.spt
Per @mcavage at https://github.com/gratipay/inside.gratipay.com/issues/1044.
=> Better emphasize the amount field on the homepage

templates/project-pagination.html
Quick fix. Eh, @mattbk @rohitpaulk @aandis @dmk246 et al.?
=> Fix project paging (#4633)

www/index.spt
=> Move "What do you use?" to follow-up

README.md
Keeps up with #4626.
Easy merge, @JessaWitzel @mattbk @clone1018 et al.
=> Update license reference in README

gratipay/homepage.py, gratipay/testing/harness.py, recreate-schema.sh, scss/pages/homepage.scss, tests/py/test_www_homepage.py, www/index.spt
Part of https://github.com/gratipay/inside.gratipay.com/issues/1160 and includes #4650.
Producing a newsletter is going to be work! Let's not overcommit ourselves.
P.S. I also looked at https://stackoverflow.com/a/39878233 for removing the value from the enum, but it left the enum with size 4 still vs. 3 as I'd expect and it made me not want to muck with pg system tables.
=> Hide monthly option

deploy/before.sql, gratipay/homepage.py, gratipay/models/payment_for_open_source.py, gratipay/testing/harness.py, scss/pages/homepage.scss, tests/py/test_www_homepage.py, www/index.spt
=> Simplify the newsletter field

gratipay/models/participant/email.py, tests/py/test_participant_emails.py, www/~/%username/emails/verify.html.spt
=> Replaces temp 'email2' field with 'email' when verifying emails

js/gratipay/homepage.js, scss/pages/homepage.scss, tests/ttw/test_homepage.py, www/index.spt
Part of https://github.com/gratipay/inside.gratipay.com/issues/1160. 💃
=> Video, etc.

scss/pages/homepage.scss, www/index.spt
Make it straightforward, don't be too cute.
=> Simplify prelaunch URL

scss/pages/homepage.scss, www/index.spt
Per https://github.com/gratipay/gratipay.com/pull/4679#issuecomment-341246316.
=> Sign in to migrate

www/index.spt
https://github.com/gratipay/inside.gratipay.com/issues/1196#issuecomment-342466613
=> Link to Bountysource

www/index.spt
Hey! I was hoping it would be ok to add Code Sponsor as a possible alternative option mentioned on the home page. Thanks @whit537!
=> Add Code Sponsor as alternate option

www/index.spt
Sorry you got squished, @cavneb. It was a good idea! 😞
http://mailchi.mp/f9b57b5ea377/code-sponsor-is-shutting-down-on-december-8
=> Remove Code Sponsor
