gratipay/gratipay.com

templates/profile.html

In general I like the reordering of profile subnav that @Changaco did in c0275a527fe26db698c7cb359752fb886be0a7f4 on #2938. However, I think Members shouldn't come between Receiving and Giving, because Receiving and Giving go together conceptually, and Members is actually less private than Receiving, since Receiving can be hidden but Members can't (once you're a team).

move Members over one

---

templates/your-tip.html

Instead of loudly advertising to users that they should stop giving to someone they're actively giving to, let's not show the Stop Giving button until the user clicks Edit.

Move the Stop Giving button under the Edit state

---

Makefile

As before, `make pytest` will run all of the Python tests.
Now you can do:
```sh
make pytest PYTEST="test_participant.py"
```
To run a single file.
Additionally, you can pass arguments to pytest:
```sh
make pytest PYTEST="test_participant.py -k about"
```

allow running a single test file w/ pytest

---

www/index.html.spt
www/opensearch.osdd

This will help our site be searchable from the omnibox on chrome and other browsers and software that use OpenSearch.

Adding opensearch definition

---

scss/gratipay.scss
scss/mixins/transform.scss
scss/molecules/feedback.scss
templates/base.html

This adds a feedback button to the side of the page which links to the issue tracker.
It should work back to IE9, which is within our support window (Current + 2 versions back)

Add feedback button

---

templates/participant.html

Right now the funding goal is obscured by being placed toward the bottom of the
page.  It's related to receiving amount, so it seems to want to have the number
there.

Add funding goal to side panel on profiles

---

gratipay/security/authentication.py
gratipay/security/csrf.py
tests/py/test_hooks.py

I was going to close #2929 as "won't fix", but then I realized that we probably don't need that Referer check, because we never send the CSRF token over insecure connections (this PR modifies a test to make sure of that).
Conflicts with #3022, I'll rebase after it's merged.

Drop referer check

---

www/%username/account/index.html.spt

Add a line break to API on account page

---

tests/py/test_privacy_json.py
www/explore/teams/index.spt

Just after we implemented search (#3066), we implemented the ability to opt out of search (#3077). This PR extends the `is_searchable` boolean to also govern inclusion in the new teams listing (#3172). When we convert communities to tags (#3127), we should extend this to govern inclusion in tag browsing as well.

opt out of search should also opt out of browse

---

js/gratipay/payments.js

Fixes #3203 by prefixing the year with `20` only if its length is 2.

Fix handling of year in credit card form

---

gratipay/main.py

For whatever reason, failures in gratipay/main.py trigger a reimport of gratipay/main.py, which trigger the warnings against double-patching Aspen, masking the real failure. Let's delay the Aspen patching to unmask these errors.

Unmask test failures related to main.py

---

www/%username/account/index.html.spt

Fixes #3130. I just remove the unused `.account-action` cell used in the PayPal section and adjust the `.account-detail` field accordingly. So now no weird table column snafus happen with long PayPal addresses.

Fix long PayPal emails breaking surrounding layout

---

Dockerfile
README.md

- Our [docker image on Docker Hub](https://registry.hub.docker.com/u/citruspi/gittip/) is outdated. Unless we setup [automated builds](http://docs.docker.com/docker-hub/builds/) or find someone who is willing to update the image regularly, a pre-built image doesn't make sense. So, I've removed the documentation for pulling from Docker Hub.
- Our `Dockerfile` now copies the repository files from context, not by cloning our GitHub repository. Before this, we were asking the user to clone our GitHub repository first, and then clone it again during the build process.
- It's now possible to execute commands such as `make schema` and `make data` within the container, documentation has been added too. Also added documentation for mounting a local folder, that's the only way people can actually …

Improve our docker experience

---

gratipay/main.py
js/gratipay/forms.js
js/gratipay/payments.js
scss/pages/cc-ba.scss
templates/profile-subnav.html
www/%username/identity.spt
www/%username/settings/close.spt
www/bank-account.html.spt
www/bank-account.json.spt
www/credit-card.html.spt
www/credit-card.json.spt

Split out identity verification from bank account connecting

---

gratipay/models/account_elsewhere.py
sql/branch.sql

Fixes #3196. We fetch the 160px-sized image instead of the old 128px one.

Update gravatar size in URL

---

Makefile
requirements.txt
requirements_tests.txt

This allows to store dependencies everythere else (#1459)
and may lead to better performance if we cache wheels,
because it looks like pip still unpacks every tar.gz regardless
of if mentioned version is already installed.

Remove paths in requirements.txt with requirement specs

---

www/about/index.spt

This is stated on the [FAQ - "How is Gratipay funded?"](https://gratipay.com/about/faq), but it's not very clear there, nor is it explicitly stated *anywhere* that Gratipay doesn't make money unless users pay it like any other account.
The FAQ probably could be updated, too, if the language I've proposed here is acceptable there, too.

Clarifies that Gratipay doesn't take a cut of payments

---

gratipay/utils/i18n.py

Currently `_("Member")` returns `('Membre', 'Membres')` (with the french locale), this PR works around that Babel defect by modifying our `get_text` function to return only the first string of the tuple.

Fix an i18n bug

---

www/%username/routes/bank-account.html.spt
www/%username/routes/credit-card.html.spt

We were filling the form fields with bad data, which results in errors for the cc form, and (what's worse) silent failures for the ba form.

Fix cc/ba forms wrt xxxxx123

---

scss/elements/buttons-knobs.scss
scss/pages/profile-edit.scss

The styling for the buttons in the add a bitcoin receiving option was a bit wonky.
Before:
After:

Clean up profile where bitcoin buttons are wrapping

---

emails/charge_failed.spt
emails/charge_succeeded.spt
emails/verification.spt
gratipay/billing/exchanges.py
gratipay/billing/payday.py
gratipay/models/participant.py
js/gratipay/settings.js
sql/branch.sql
tests/py/test_billing_payday.py
tests/py/test_email_notifs.py
www/%username/emails/notifications.json.spt
www/%username/settings/index.html.spt

notify users of card charges

---

www/%username/identity.spt

It seems to make sense that this field wouldn't be shown on-screen while you're punching your info in.

Change SSN field to password field

---

templates/avatar-url.html

Reference to issue #3381. It's described [here](https://de.gravatar.com/site/implement/images/) that you can resize gravatar images. Since 320px is the double of 160px, the gravatar should also be retina ready.

Avoid blurry images and be retina ready

---

tests/py/test_pages.py
tests/py/test_routes.py
www/%username/routes/bank-account.html.spt
www/%username/routes/credit-card.html.spt
www/about/migration.spt

Ping @rohitpaulk @techtonik @clone1018 et al. This addresses https://github.com/gratipay/gratipay.com/issues/3391#issuecomment-100399161.

Temporarily disable route changes during migration

---

Makefile
README.md

We introduced a `data` directory in #3329, which masks our phony target for populating the database with fake data. This cherry-picks d6372ed21e370bb83ea99ac45e90605e6074b405 from #3400.

Rename `make data` to `make fake`

---

gratipay/models/team.py
gratipay/testing/__init__.py
gratipay/wireup.py
tests/py/test_teams.py

For #3399. cc: @rohitpaulk 
On #3400 I tried promoting `MixinTeam` to `Team` in one fell swoop. It occurs to me that it will be easier to develop if we let them live side by side for a time. This PR therefore adds a `Team` class without touching `MixinTeam`. We can move functionality over from the one to the other piecemeal in other PRs, and remove `MixinTeam` once it's finally empty.

here's a Team class

---

gratipay/models/participant.py
gratipay/models/team.py
js/gratipay/new_team.js
tests/py/test_routes.py
tests/py/test_teams.py
www/new.spt
www/teams/create.json.spt

Team creation

---

gratipay/models/participant.py

Fixes a bug reported in https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-102053074. 
> I got error "400 Bad Request: You must attach a bank account or PayPal to apply for a new team." although ~NuvolaPlayer does have PayPal account attached.

Fix paypal bug for new teams

---

gratipay/models/__init__.py
sql/payday.sql
tests/py/test_billing_payday.py

https://github.com/gratipay/gratipay.com/pull/3414#commitcomment-11203627

Fix payment table semantics

---

sql/payday.sql
tests/py/test_billing_payday.py

Includes #3430.
This fixes the tests that are [failing on master](https://travis-ci.org/gratipay/gratipay.com/builds/62612543) (without test fixtures)

Payday fixes

---

gratipay/billing/payday.py
tests/py/test_billing_payday.py

https://github.com/gratipay/gratipay.com/issues/3415#issuecomment-102459522
#3396

Constrain payday payouts

---

bin/masspay.py

This uses the same condition we added to `Payday.payout` in #3438.

constrain payouts via MassPay

---

templates/base.html
tests/js/test_homepage.js
tests/py/test_hooks.py
www/index.html.spt

I tried implementing this using our js notification system, but that doesn't support HTML that I can tell. I wanted to include links. The content area is the best place I could quickly find to put this (works properly across the full range of viewport sizes), but that's not available on the unauthenticated homepage, so as a quick hack this PR additionally redirects `/` to `/about/` for anon.
Addresses #3447.

add a global notice about site disruption

---

sql/branch.sql
tests/py/test_teams.py
www/%team/index.html.spt
www/new.spt
www/teams/create.json.spt

Closes #3456. Ready for review, @rohitpaulk et al.

split out revenue model as a separate question

---

www/%team/subscription.json.spt

[ref](https://github.com/gratipay/gratipay.com/pull/3467#issuecomment-104440521).

show appropriate message when canceling a payment

---

www/%team/index.html.spt

Our team application and approval process calls for a public community comment period, which means that Gratipay users need to be able to see the teams in question.

allow all authenticated users to see all teams

---

gratipay/models/team.py
tests/py/test_teams.py
www/teams/create.json.spt

fix bug with revenue model

---

npm-shrinkwrap.json
package.json

If it won't break Travis, using latest package
version will make troubleshooting #3000 easier.
Regenerating npm dependency resolution cache:
$ rm npm-shrinkwrap.json
$ npm shrinkwrap --dev

Update grunt-webdriver 0.4.4 -> 0.5.1 for jstest

---

gratipay/models/team.py
tests/py/test_teams.py

Create a migrate tips function

---

bin/migrate-tips.py

This is the script from https://github.com/gratipay/gratipay.com/issues/3486#issuecomment-106630168. 
Since we're going to run this every week until the period for migrating to teams ends, I thought storing it in the repo would be a good idea.

Add script for migrating tips to new teams

---

sql/payday.sql
tests/py/test_billing_payday.py

stop charging failed cards

---

bin/masspay.py
gratipay/billing/exchanges.py
gratipay/billing/payday.py
sql/branch.sql
tests/py/test_billing_payday.py

implement a flag for paying out Gratipay 1.0 balances

---

www/dashboard/teams.spt

It's helpful to see the actual team page, first because we never added the revenue model question to the review dashboard, but also for context like the owner.

Drop back to iframe for team review

---

tests/py/test_is_suspicious.py
www/dashboard/index.spt
www/~/%username/toggle-is-suspicious.json.spt

point user review dashboard to ~new place

---

gratipay/billing/instruments.py

#3533
I'm not adding extra tests for this, checked that it works by setting `card.billing_address = None` just before where I made the change.

Check for null billing_address in billing/instruments.py

---

gratipay/utils/fake_data.py
tests/py/test_fake_data.py

Fake data script updated to create teams and subscriptions.
Fake data test script updated accordingly.

fake-data, teams and subscriptions

---

data/routing.txt

Needs to check that decommission dates are right and add references to verbose explanations.
Closes #3521

data/routing: -Bitcoin +Braintree

---

gratipay/utils/history.py
tests/py/fixtures/TestHistory.yml
tests/py/test_billing_payday.py
tests/py/test_history.py
www/~/%username/history/index.html.spt

update history page

---

gratipay/cli.py

https://github.com/gratipay/gratipay.com/issues/3641#issuecomment-124244919

prune references to dead sync_with_balanced

---

tests/py/test_pages.py
www/index.html.spt
www/~/%username/giving/index.html.spt

#3599 is a :rabbit2: hole. Here's a quick fix that drops back to computed rather than cached values.

fix giving amounts in the UI

---

templates/profile-subnav.html

Removed link to widgets because widgets are not currently correct and
not hooked up to teams.  https://github.com/gratipay/grtp.co/issues/103

Removed widgets link on profile

---

gratipay/models/team.py
www/%team/index.html.spt

"Rejecting" teams is too harsh a term for the situation we want to optimize for, wherein we reach a decision collaboratively together with team owners about whether they and we are a good fit for each other. I think we should use the term "close" instead. That leaves ambiguous the circumstances surrounding the closing, whereas "rejected" only covers the harshest case, wherein Gratipay acts despite the owner's intention. A "closed" account could be closed by the owner's decision, by Gratipay's, or by both agreeing together.

rejected -> closed

---

gratipay/models/team.py

Sorry for the run-around on this, @mattbk @rohitpaulk et al. This PR backs out #3678. The reason is that I tried using the word "closed" ... somewhere (can't find it atm), and it sounded like doublespeak. Like, if we *did* reject someone but said the account was "closed" then that implies *they* closed their account—otherwise how are we going to distinguish that case? Let's use "rejected" for when we reject a team, and "closed" for when the owner closes the team, which could be before or after we review them. This PR reinstates "rejected", and we'll need #3602 for closing.

actually, let's use rejected

---

CONTRIBUTING.md

Check this from the [CC0 webpage](https://creativecommons.org/publicdomain/zero/1.0/legalcode):
>  Public License Fallback. Should any part of the Waiver for any reason be judged legally invalid or ineffective under applicable law, then the Waiver shall be preserved to the maximum extent permitted taking into account Affirmer's express Statement of Purpose. In addition, to the extent the Waiver is so judged Affirmer hereby grants to each affected person a royalty-free, non transferable, non sublicensable, non exclusive, irrevocable and unconditional license to exercise Affirmer's Copyright and Related Rights in the Work (i) in all territories worldwide, (ii) for the maximum duration provided by applicable law or treaty (including future time extensions), (iii) in any current or future …

Removed misleading "i.e it's public domain"

---

tests/py/test_teams.py

Cherry-picked from #3675 (a parallel commit, a5cef34ba9d87ea5ea87d4ee4305aa292db5f876, was on #3568).

add an order clause to eliminate an occasional error

---

tests/py/test_participant.py

The problem is that we introduced `~` as a restricted name (it's a directory name), but it's also an invalid character, and the invalid character was getting flagged in the test for name restriction.
Fixes #3696.

fix intermittent test failure

---

gratipay/models/team.py
gratipay/testing/__init__.py
gratipay/utils/fake_data.py
js/gratipay/team.js
sql/branch.sql
tests/py/test_teams.py
www/%team/index.html.spt
www/new.spt
www/teams/create.json.spt

revise the Team application

---

www/about/features/payments.spt

Closes #1273.
What else should we list besides [*Traction*](http://tractionbook.com/)?
Any suggestions, @webmaven? :-)

let's point folks to a few resources for marketing advice

---

www/index.html.spt

Didn't before because the welcome started life before cache values were rationalized (#3721).

include dollars in the welcome

---

scss/pages/homepage.scss
www/index.html.spt

Advertise Team creation on the homepage! We have About pages now that explain it.

open the floodgates

---

gratipay/billing/payday.py
gratipay/models/participant.py
sql/branch.sql
sql/payday.sql
sql/schema.sql
tests/py/fixtures/TestPayday.yml
tests/py/test_billing_payday.py
tests/py/test_history.py

Implemented the core part of the solution for issue "charge minimum in arrears, not in advance #3378" 
Overview of the solution:
i) Added a new column giving_due in payment_instructions. To be populated/incremented with the corresponding amount, each time the amount is not charged due to being under the minimum charge threshold
ii) After creation of payday_payment_instructions, the giving_due value for each participant-team combination is updated with the sum of giving_due values for that combination, from payment_instructions. 
iii) The 'giving_today' value for each participant is calculated as sum(amount + giving_due) from all records for that participant in payday_payment_instructions
iv) The 'giving_today' value is checked against the MINIMUM_CHARGE threshold before creating card …

Charge in arrears

---

gratipay/models/team.py
scss/components/status-icon.scss
scss/elements/elements.scss
scss/gratipay.scss
scss/layouts/layout.scss
scss/layouts/responsiveness.scss
scss/pages/homepage.scss
templates/base.html
www/%team/index.html.spt
www/index.html.spt

Gonna leave this one sit a few days. We need to stop having me merge my own pull requests!
Ping @mattbk @rohitpaulk @techtonik @kzisme @kaguillera @clone1018 et al.
Who wants to merge this one? :-)

preen layout

---

gratipay/models/team.py

Drop the redundant "review" (we now have a dedicate repo) and add the helpful note about it taking a week.
Follow-on from #3568.

tinker with automated Team review ticket

---

www/%team/index.html.spt

fix regression in status icons on Team pages

---

gratipay/billing/payday.py
sql/branch.sql
sql/payday.sql
tests/py/test_billing_payday.py

Using Python string interpolation on the `payday.sql` file introduces complexity that leads to bugs. The one I hit was using `%` for interpolation in a Postgres `RAISES` clause: it would've had to be escaped to make it through the Python interpolation.
I cherry-picked this from 364d066bb4e7f69b7a2febc31230fdb8e57b05a6 in #3653.
See reference in https://github.com/gratipay/gratipay.com/issues/3780#issuecomment-139909299.

stop Python-interpolating payday.sql

---

gratipay/utils/fake_data.py
tests/py/test_fake_data.py

We removed a number of payday stats fields in #3730, but were still trying to populate those in fake data. This PR also makes db cleaning a little more robust so we can recover from failure during `make fake`.
Fixes #3780.

catch fake data up with #3730

---

gratipay/utils/__init__.py

The `update_cta` function updates the statistics we use in our global call to action (cta). We have defaults for development, where the database can be empty. This runs in a thread and was causing logspam and actually a test failure on forthcoming commits for #3788.
Fixes #3771.

fix default for nusers in update_cta

---

www/1.0-payout.spt

We published a blog post that says you can still withdraw 1.0 money, but this page has a deadline built into it.  As a stopgap, extended deadline to Oct 2, 2115.

Extend 1.0 payout deadline 100 years

---

sql/schema.sql
tests/py/test_members_json.py

I discovered that we apparently never applied these last two `branch.sql`s(?!), and when I went to apply them I hit a syntax error with the first, and another error with the second (`ERROR:  ALTER TYPE ... ADD cannot run inside a transaction block`). I've run these modified commands against production.

repair schema sql

---

gratipay/models/participant.py
sql/branch.sql

This pr only introduces a new column in `emails` table which references `participants.id` and modifies email writes to include `email.participant_id` as well. Ideally we would want this to be deployed before we start copying old values from `participant.id` to `email.participant_id`. So that would come in a separate migration.

Change emails foreign key

---

gratipay/models/participant.py
sql/branch.sql
tests/py/test_email.py

This is the next step after #3893. Pr includes a migration to fill the new `emails.participant_id` column with existing data and modifies email reads to then read from the new column instead of `emails.participant`.

Change emails foreign key - 2

---

www/dashboard/reconciliation.spt

This is to support our new financial accounting system. See https://github.com/gratipay/finances/pull/1.

add a reconciliation dashboard

---

bin/masspay.py
payday.sh

Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/477#issuecomment-173662313.

tweak masspay scripts

---

gratipay/models/participant.py
sql/branch.sql

Last step for changing emails table. Changes writes to only use `participant_id` and drops `participant` column.
EDIT by @rohitpaulk: 
Issue: https://github.com/gratipay/gratipay.com/issues/835
Follows https://github.com/gratipay/gratipay.com/pull/3893 and https://github.com/gratipay/gratipay.com/pull/3896

Change emails foreign key - 3

---

.travis.yml

This sets us up to configure private Travis for the security repo, and close https://github.com/gratipay/inside.gratipay.com/issues/456.

turn off IRC notifications at Travis

---

bin/migrate-tips.py
gratipay/models/team.py

@rohitpaulk , @whit537 tests are failing as of now. If this looks good, I'll go ahead and fix them. ;)
https://github.com/gratipay/gratipay.com/issues/3894

Speed up tip migration. Fixes #3894

---

README.md

I've just fixed an invalid link in the API section in README.md file.

Fixing an invalid link in README.md file

---

README.md
tests/py/test_payment_instructions_json.py
www/~/%username/payment-instructions.json.spt

Still WIP.
Added `GET` to show all subscriptions of a user along with filtering on team slug.
References #3460

Subscriptions api

---

README.md

Fix `/~username/payment-instructions.json` link.
Very similar change to #3910.

README: Fix broken link in API section.

---

payday.sh

@clone1018 @rohitpaulk Did you not get bit by this? The path is [`payday`](https://github.com/gratipay/logs/tree/master/payday), not `paydays`. Crept in in #3901, prior to that I had symlinks masking the issue.

Tweak paths to payday logs

---

gratipay/exceptions.py
gratipay/models/team.py
gratipay/utils/fake_data.py
tests/py/fixtures/TestTeams.yml
tests/py/test_teams.py
www/new.spt
www/teams/create.json.spt

Team name restrictions

---

gratipay/models/participant.py
gratipay/utils/__init__.py
tests/py/test_email.py
tests/py/test_utils.py
www/~/%username/emails/verify.html.spt

Let's fix #3110. I don't know yet what the issue is, but so far here's a *passing* test for escaping plusses in emails in the links we send out. At what point are those getting unescaped?

fix plusses in emails

---

gratipay/main.py
tests/py/test_security.py

We're ending up with 500 instead of 405, because of a misordering in the algorithm functions. The error handling needs a `user` object, and also apparently some `i18n`.
This surfaced on [H1-127218](https://hackerone.com/reports/127218).

fix method whitelisting

---

www/dashboard/index.spt

This changes the condition by which we filter users for review.
The new conditions are:
1) The user must have tips setup with a net value > 0. (And this should be calculated without using cached values)
2) The user must have a payin/payout route attached.

Fix review dashboard, fixes #3937

---

payday.sh

Found this when running https://github.com/gratipay/inside.gratipay.com/issues/562 on a droplet

Fix how payday checks for required commands

---

sql/branch.sql
sql/payday.sql
tests/py/test_billing_payday.py

This is a redo of https://github.com/gratipay/gratipay.com/pull/3876 with a cleaner commit log.

Cap unfunded dues

---

bin/rekey.py
gratipay/models/country.py
gratipay/models/participant/__init__.py
gratipay/models/participant/mixins/__init__.py
gratipay/models/participant/mixins/identity.py
gratipay/wireup.py
sql/branch.sql
tests/py/test_close.py
tests/py/test_participant.py
tests/py/test_participant_identities.py
tests/py/test_security.py

&#x2B11; #3994
&#x2B11; #3976
#4001 &rarr;

Encrypted identities

---

gratipay/models/participant/mixins/identity.py
sql/branch.sql
tests/py/test_participant_identities.py

add schema and Python for [un]verifying identities

---

gratipay/utils/fake_data.py
tests/py/test_fake_data.py
www/dashboard/countries.spt

&#x2B11; #3994
&larr; #4003 — #4007 &rarr;
This gives us tools to develop UI around participant identities.

fake identities, with dashboard

---

bin/migrate-tips.py
gratipay/models/__init__.py
gratipay/models/team.py
tests/py/test_teams.py
tests/py/test_tip_migration.py

A lack of test coverage of the `bin/migrate-tips.py` script surfaced during a refactor (#4046). Therefore, here we:
- Move heavy lifting from the `bin/migrate-tips.py` executable into a `migrate_all_tips` function in the gratipay library for easier testing
- Split out tip migration tests into their own test script
- Add a few tests for `migrate_all_tips`

Refactor tip migration

---

Procfile
hide_gunicorn_version.py

This is a slight security improvement.
https://hackerone.com/reports/123742
Verified working in a sandbox:
```
$ curl -IL http://gratipay537.herokuapp.com/
HTTP/1.1 200 OK
Connection: keep-alive
Server: gunicorn
Date: Tue, 14 Jun 2016 16:13:59 GMT
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Gratipay-Version: 1967
X-Xss-Protection: 1; mode=block
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache
Set-Cookie: csrf_token=[]; expires=Tue, 21 Jun 2016 16:13:59 GMT; Path=/
Via: 1.1 vegur
$
```

Hide gunicorn version

---

gratipay/exceptions.py
gratipay/models/participant/__init__.py
templates/your-payment.html
tests/py/test_billing_payday.py
tests/py/test_pages.py
tests/py/test_participant.py
www/about/pricing.spt

This simplifies three APIs that previously accepted *either* a Team object *or* a slug. They now only accept a Team object. The reason is that the additional flexibility wasn't adding much value for the additional complexity. 
Salvaged from #4046.

Simplify some APIs to not take Team slugs

---

gratipay/models/participant/__init__.py
gratipay/models/team.py
gratipay/utils/fake_data.py
sql/branch.sql
tests/py/test_participant.py
tests/py/test_tip_migration.py

first step of 835 for payment_instructions

---

gratipay/billing/payday.py
gratipay/models/participant/__init__.py
gratipay/models/team.py
sql/branch.sql
sql/payday.sql
tests/py/test_billing_payday.py
tests/py/test_close.py
tests/py/test_participant.py
tests/py/test_teams.py
tests/py/test_tip_migration.py
www/about/payment-distribution.json.spt
www/dashboard/index.spt

Backfills new columns and starts reading from them.

second step of 835 for payment_instructions

---

gratipay/models/participant/__init__.py
gratipay/models/team.py
gratipay/utils/fake_data.py
sql/branch.sql
tests/py/test_tip_migration.py

third step of 835 for payment_instructions

---

docs/autolib.py
gratipay/models/team/__init__.py
gratipay/models/team/mixins/__init__.py
gratipay/models/team/mixins/tip_migration.py
tests/py/test_tip_migration.py

&#x2B11; #3994
&larr; #4068 ([diff](https://github.com/gratipay/gratipay.com/compare/refactor-tip-migration...docs-source-order)) — #4072 &rarr;
Using source order for docs gives us more control and aligns docs with source code.

use source order for docs

---

gratipay/testing/__init__.py
tests/test.env

test helpers

---

gratipay/models/participant/__init__.py
gratipay/models/team/mixins/takes.py
tests/py/test_participant.py
tests/py/test_team_takes.py

&#x2B11; #3994
&larr; #4094 ([diff](https://github.com/gratipay/gratipay.com/compare/require-docs...update-some-python-APIs)) — #4077 &rarr;
This fixes a few bugs and warts with Python APIs that we want to use in bringing back the takes UI.

update some python APIs

---

gratipay/models/participant/__init__.py
tests/py/test_participant.py
tests/py/test_username_json.py

This aims to fix [H1-128121](https://hackerone.com/reports/128121). 
We're currently listing all the existing files inside `www_root` and comparing the username to each file/folder to ensure an user won't try to use it. However, there is a mapping between the files and the website route (`lookup.json.spt` is served as`lookup.json`), so the comparison is little bit more complicated.
I'm just adding a list of forbidden extensions, and it will to to match the list of files with `username`, `username.txt`, ... It won't really affect performances since it's only called when creating an account or changing the username. I would really know if somebody has a more elegant way to do it 🐱

Fix usernames restriction

---

gratipay/models/community.py
gratipay/utils/fake_data.py
tests/py/test_fake_data.py

This should fix the issue #3722

Fix for #3722

---

tests/py/test_statement_json.py
www/~/%username/statement.json.spt

This aims to close [H1-127824](https://hackerone.com/reports/127824). When parsing very large user statements, the markdown parser may take too much resources. We are already safe against nested elements attacks.
**Questions**: 
- should we restrict the "product or project" field for teams? The teams are manually reviewed and they don't have any interest in voluntarily slowing down the display of their pages.
- should we add one hard limit on the database field? It's hard to predict, since we (want to) restrict the size before the md-to-html translation process.

Limit user statement size

---

gratipay/models/team/mixins/takes.py

We should avoid gender-specific pronouns in non-specific contexts.

Remove gendered pronoun

---

gratipay/billing/payday.py
gratipay/models/team/mixins/takes.py
sql/payday.sql
tests/py/test_billing_payday.py

&#x2B11; #3994
&larr; #4077 — #4113 &rarr;
Remake of #4025.
- obviated by rebased commits 0ed1d311207bff90eca77686c177bc0e94657a8d and 51af22746bd7595170125f2f6298bc2755e0fa1e

Bring back takes in payday

---

bin/masspay.py
gratipay/billing/exchanges.py
gratipay/testing/billing.py
tests/py/fixtures/TestsWithBillingHarness.yml
tests/py/test_billing_exchanges.py

&#x2B11; #3994
&larr; #4113 ([diff](https://github.com/gratipay/gratipay.com/compare/takes-test-refactor...takes-masspay))

Include team members in MassPay

---

gratipay/utils/fake_data.py
tests/py/test_fake_data.py

Added fake subscriptions and payments. Tests have been correspondingly updated.
Tips and transfers have been left as they are, for removal later once migration is complete.
This is ready for review.
Please note one change in particular that needs to be validated, made for week_tips and week_transfers (and the new week_subscriptions and week_payments):
week_tips = filter(lambda x: date <= x['ctime'] < end_date, tips)
was
week_tips = filter(lambda x: date < x['ctime'] < end_date, tips)
Seemed to me that transactions at min_date were being skipped in processing due to the 'date < x['ctime']' condition. This wasn't causing any issues, because this would correspondingly not have gone into exchanges as well.

Fake data - subscriptions and payments

---

.travis.yml
gratipay/utils/markdown.py
tests/py/test_markdown.py

[marky-markdown](https://github.com/npm/marky-markdown#command-line-usage) is the markdown parser that npm uses. We should use it with npm package readmes. There's a [CLI](https://github.com/npm/marky-markdown#command-line-usage) that we should be able to wrap. It doesn't take `stdin` but we can work around that using `/dev/stdin` like so:
```
marky-markdown /dev/stdin
```

Wrap marky-markdown

---

www/search.spt

Closes #3382.
If you are an admin, search will return users whose email address (in `participants`) matches the query. If you are not an admin, you won't notice the functionality (or lack of).
One thing I couldn't figure out was how to match partial strings. E.g., searching for `alice` returns both ~user Alice (on `username`) and ~user Alice (on `email_address` alice@example.com), searching for `al` only returns Alice on `username`. However, for support cases, I don't think this is a huge problem because we have the entire email address to search with (as long as they contact us with the email address in the database).

Allow admins to search by email

---

.travis.yml
gratipay/package_managers/sync.py
tests/py/test_npm_sync.py

Fix npm sync bug with empty descriptions

---

bin/sync-npm.sh
gratipay/billing/payday.py
gratipay/package_managers/readmes.py
gratipay/package_managers/sync.py
gratipay/utils/markdown.py
gratipay/utils/threaded_map.py
sql/branch.sql
tests/py/test_npm_sync.py

Here's a first crack at syncing readmes

---

Makefile
requirements.txt

Heroku doesn't run `make env`, they simply `pip install -r requirements.txt`. We want ourself installed in the virtualenv in order to be able to run scripts.

Install self in requirements.txt

---

gratipay/package_managers/sync.py

It requires heavy dependencies.

Avoid ijson if we can help it

---

templates/profile.html

Fixes https://github.com/gratipay/gratipay.com/issues/3906. 
Intentionally kept this simple - I've only modified the left-nav text, the route URL (`/~user/routes`) and headings ('Payment Routes') are untouched.
**After:**
**Before:**

Rename 'Routes' to 'Payments'

---

gratipay/package_managers/sync.py
tests/py/test_npm_sync.py

Should address at least some of https://github.com/gratipay/gratipay.com/pull/4172#issue-187266655.

Fix build breakage introduced in npm syncing

---

gratipay/package_managers/readmes.py
tests/py/test_npm_sync.py

Part of #4148.
https://github.com/gratipay/gratipay.com/issues/4148#issuecomment-259322332

Fix npm sync regression

---

tests/py/test_hooks.py
tests/py/test_security_csrf.py

Redux of #4184 (I couldn't help but close it in the course of https://github.com/gratipay/inside.gratipay.com/issues/884#issuecomment-260035697).
--------------------
We're getting [a ridiculous number](https://sentry.io/gratipay/gratipay-com/issues/79907897/) of `TypeError`s from trying to `constant_time_compare` one or two `None`s. Sup with that?

Fix CSRF annoyance

---

gratipay/models/team/mixins/membership.py
gratipay/models/team/mixins/takes.py
gratipay/testing/billing.py
tests/py/test_billing_exchanges.py
tests/py/test_team_membership.py
tests/py/test_team_takes.py

Update tests for new mixins

---

deploy.sh

I want it at the end, actually. 😁 
Follow-on from #4202.

Tweak deploy confirmation

---

www/1.0-payout.spt
www/new.spt

Let's still keep the database table there, but let's cut out the ~~Python and~~ (https://github.com/gratipay/gratipay.com/issues/4148#issuecomment-264540868) front-end.
See https://github.com/gratipay/inside.gratipay.com/issues/536.

Remove tips from the UI

---

www/about/policies/terms-of-service.md

https://github.com/gratipay/inside.gratipay.com/issues/432#issuecomment-243522286
> I've started a [private ticket](https://github.com/gratipay/legal-tor-ekeland/issues/31) with our [lawyer](https://github.com/copiesofcopies) about revising our Terms of Service to relax our open work requirement. In the interest of time/money, I think the way to proceed is **take a stab at revising them ourselves**, and then bring our revision to him for review.
Stub out a PR for changes.
Related milestones:
- IG: https://github.com/gratipay/inside.gratipay.com/milestone/9
- G: https://github.com/gratipay/gratipay.com/milestone/22
- Tried to address in https://github.com/gratipay/gratipay.com/pull/4117/commits/78edd7983ec2ca316db9b5fd0cb5212e763d8822 by creating "Giver"
- Tried to address in …

Edit TOS to decouple payins and payouts

---

gratipay/models/team/__init__.py
gratipay/testing/harness.py
gratipay/utils/fake_data.py
sql/branch.sql
sql/schema.sql
tests/py/test_team_edit.py
tests/py/test_teams.py
www/%team/edit/edit.json.spt
www/%team/edit/index.html.spt
www/%team/index.html.spt
www/new.spt
www/teams/create.json.spt

Remove the To-do URL

---

gratipay/utils/fake_data.py

First attempt in #4224 didn't work: https://github.com/gratipay/gratipay.com/pull/4221#issuecomment-265572804.

Fix Faker again

---

gratipay/models/team/__init__.py
tests/py/test_team_edit.py
tests/py/test_teams.py
www/%team/edit/edit.json.spt
www/%team/edit/index.html.spt
www/%team/index.html.spt
www/new.spt
www/teams/create.json.spt

Derived from https://github.com/gratipay/gratipay.com/issues/4123.
Stubbing this out, need to be on front of a local install before I can do more (aside from learning Aspen).

Revise the New Project form

---

www/about/index.spt

Bug from #4221.
We don't have Markdown here; use HTML.

Fix link in About page

---

gratipay/security/__init__.py
tests/py/test_security.py

This solves the following report: https://hackerone.com/reports/90777
This policy allows:
- Resources from gratipay.com & all gratipay subdomains.
- Fonts from cloud.typography.com.
If you like we could allow GIFs from, for example, [giphy.com](https://giphy.com/). That way users can at least embed GIFs.
Concerning [report-uri.io](https://report-uri.io/), you will need to sign up for that and if you have any issues feel free to contact me.

Implement Content-Security-Policy (CSP)

---

gratipay/security/__init__.py
tests/py/test_security.py

Implement a content security policy

---

.travis.yml
bin/sync-npm.sh

Repo size reduce from 2084 KB to 1156 KB, we can save time, bandwidth and disk space, and a `checkout` command/process from this change.

Improve git clone process, save time, bandwidth and disk space

---

gratipay/utils/emails/queue_branch_email.py
tests/py/test_email.py

Picking up from https://github.com/gratipay/gratipay.com/pull/4232#issuecomment-271026845 ...

Finish sending out Terms notification

---

gratipay/models/participant/__init__.py
gratipay/models/team/__init__.py
gratipay/models/team/mixins/__init__.py
gratipay/models/team/mixins/closing.py
gratipay/testing/harness.py
js/gratipay/edit_team.js
scss/components/danger-zone.scss
scss/components/long-form.scss
scss/elements/buttons-knobs.scss
templates/team-listing.html
tests/py/test_close.py
tests/py/test_pages.py
tests/py/test_participant.py
tests/py/test_team_closing.py
www/%team/edit/close.spt
www/%team/edit/index.html.spt
www/assets/gratipay.css.spt
www/index.html.spt
www/~/%username/settings/close.spt
www/~/%username/settings/index.html.spt

Implement project (Team) closing

---

tests/ttw/test_team_distributing.py

Trying to avoid spurious test failures.
https://travis-ci.org/gratipay/gratipay.com/builds/191469577

Tinker with timing for Travis

---

gratipay/models/participant/__init__.py
scss/components/danger-zone.scss
tests/py/test_close.py
www/%team/edit/index.html.spt
www/%team/index.html.spt
www/~/%username/identities/%country.spt
www/~/%username/settings/close.spt
www/~/%username/settings/index.html.spt

Following on from #4291 (which is included here), this adds a danger zone to the top of the project page, which is still accessible to owners and admins.

Show as closed

---

gratipay/models/participant/__init__.py
scss/components/danger-zone.scss
tests/py/test_close.py
www/~/%username/settings/close.spt

Impetus was bugs discovered at https://github.com/gratipay/gratipay.com/issues/3602#issuecomment-272541653.
- fix bugs in balance checking (`> 0` vs `!= 0`)
- allow admins to close accounts w/ balance
- refactor test suite a little bit
- add tests

Improve logic in account closing

---

gratipay/main.py
gratipay/utils/__init__.py
sql/branch.sql
tests/py/test_acme_challenge.py
www/.well-known/README
www/_well-known/acme-challenge/%token.spt

StartSSL is hosed, so we need a new TLS cert vendor (https://github.com/gratipay/gratipay.com/issues/4327). Let's Encrypt suggests itself, but we need a way to pass verification challenges for multiple domains. Let's build a way!

Rise to the ACME challenge

---

gratipay/utils/__init__.py
gratipay/wireup.py
tests/py/test_acme_challenge.py
www/_well-known/acme-challenge/index.spt
www/assets/.well-known/README
www/assets/_well-known/acme-challenge/%token.spt

- mount read-only under /assets/
- display a count for admins on ./
Ready for review, @clone1018 et al.

Extend the ACME challenge system

---

bin/masspay.py
tests/py/fixtures/TestNMassPays.yml
tests/py/test_dashboard.py
www/dashboard/nmasspays.spt

Hopefully will prevent recurrences of https://github.com/gratipay/inside.gratipay.com/issues/951#issuecomment-268832559.

Implement a check for whether we posted MassPay

---

tests/ttw/test_team_distributing.py

In the grand tradition of #4129 and #4290 ...

Fix travis failure

---

gratipay/security/__init__.py
templates/base.html
tests/py/test_security.py

Set the `Referrer-Policy` to `strict-origin-when-cross-origin`. This
should boost our grade on
https://securityheaders.io/?q=gratipay.com&hide=on&followRedirects=on.

Add "Referrer-Policy" header

---

gratipay/models/participant/__init__.py
gratipay/models/participant/email.py
gratipay/testing/emails.py
tests/py/test_email.py

https://github.com/gratipay/gratipay.com/pull/4335 turned up some dryrot. This is a start on cleaning it up.

Improve email subsystem

---

deploy.sh
gratipay/wireup.py

Closes #4364. Python's [`-m`](https://docs.python.org/2/using/cmdline.html#cmdoption-m) does not perform the `sys.path` manipulations that got us in trouble.

Fix regression in deployment

---

bin/masspay.py
tests/py/test_dashboard.py
www/dashboard/nmasspays.spt

Addresses https://github.com/gratipay/inside.gratipay.com/issues/1013#issuecomment-283656746.

Fix nmasspays check during payday

---

gratipay/application.py
gratipay/billing/payday.py
gratipay/cli/payday.py
gratipay/payday_runner.py
gratipay/testing/billing.py
gratipay/testing/harness.py
gratipay/website.py
tests/py/test_billing_payday.py
tests/py/test_close.py
tests/py/test_history.py
tests/py/test_paydays_json.py

Properly speaking, we should have zero global configuration. Everything should hang from a `Gratipay` object that we instantiate for gunicorn and in scripts. But for https://github.com/gratipay/gratipay.com/pull/4346#discussion_r102598587 we at least need to make the `application` object accessible from within `Payday`.

Use Application in Payday

---

gratipay/__init__.py
gratipay/application.py
gratipay/cli/queue_branch_email.py
gratipay/exceptions.py
gratipay/fake_data.py
gratipay/models/__init__.py
gratipay/models/exchange_route.py
gratipay/models/participant/__init__.py
gratipay/models/participant/email.py
gratipay/models/participant/identity.py
gratipay/models/team/__init__.py
gratipay/models/team/closing.py
gratipay/testing/harness.py
gratipay/utils/__init__.py
gratipay/utils/i18n.py
gratipay/version.py
gratipay/website.py
gratipay/wireup.py
tests/py/test_email.py
tests/py/test_take_over.py
www/%team/set-status.json.spt
www/~/%username/payout-status.spt
www/~/%username/toggle-is-suspicious.json.spt

Picking up from #4345:
- Clear out `gratipay/__init__.py` as part of moving away from global config.
- Make `.app` available on models.
- Simplify `website.version`.

Further Application improvements

---

bin/masspay.py

New comprehensive application wiring was tripping up on this.
https://github.com/gratipay/inside.gratipay.com/issues/1024#issuecomment-288837559

Avoid chdir in masspay

---

tests/py/test_elsewhere.py
www/on/confirm.html.spt

Our app is no doubt rife with this sort of thing, no energy for a root cause fix atm though. Just playing whack-a-mole with security researchers.
https://sentry.io/gratipay/gratipay-com/issues/242266718/

Squish little annoying bug in confirm.html

---

gratipay/models/package/__init__.py
gratipay/models/participant/email.py
gratipay/models/team/__init__.py
gratipay/models/team/package.py
sql/branch.sql
tests/py/test_email.py
tests/py/test_packages.py
tests/py/test_take_over.py
www/~/%username/emails/modify.json.spt
www/~/%username/emails/verify.html.spt

Part of #4305, follow-on from #4335.
(9) from the [workflow](https://github.com/gratipay/gratipay.com/issues/4297#issuecomment-273900610) &hellip; the big one!
> (9) hit /on/npm/react/claim

Receive package claim link-back

---

gratipay/exceptions.py
gratipay/models/package/__init__.py
gratipay/models/team/__init__.py
gratipay/typecasting.py
gratipay/utils/__init__.py
gratipay/website.py
tests/py/test_packages.py
tests/py/test_pages.py
tests/py/test_teams.py
tests/py/test_utils.py
tests/py/test_www_npm_package.py
tests/py/test_www_team_receiving.py
www/%team/charts.json.spt
www/%team/distributing/%to.json.spt
www/%team/distributing/index.html.spt
www/%team/distributing/index.json.spt
www/%team/edit/close.spt
www/%team/edit/edit.json.spt
www/%team/edit/index.html.spt
www/%team/history/index.html.spt
www/%team/image.spt
www/%team/index.html.spt
www/%team/payment-instruction.json.spt
www/%team/public.json.spt
www/%team/receiving/index.html.spt
www/%team/set-status.json.spt
www/on/npm/%package/index.html.spt
www/~/%username/receipts/%exchange_id.html.spt

Part of #4305, follows on #4397.

Present claimed packages as projects

---

gratipay/models/package/__init__.py
gratipay/models/package/team.py
gratipay/models/team/package.py
tests/py/test_packages.py

Part of #4305, follows on #4404.
Minor refactor. Ready for review.

Factor out a package.team mixin

---

401.spt
410.spt
gratipay/testing/harness.py
gratipay/utils/icons.py
js/gratipay/packages.js
js/gratipay/select.js
scss/components/dropdown.scss
scss/components/listing.scss
scss/components/nav.scss
scss/components/select.scss
scss/components/sign_in.scss
scss/components/status-icon.scss
scss/components/text-treatments.scss
scss/elements/buttons-knobs.scss
scss/layouts/layout.scss
scss/pages/package.scss
templates/base.html
templates/project-listing.html
templates/sign-in-using.html
templates/your-payment.html
tests/py/test_routes.py
tests/ttw/test_package_claiming.py
www/%team/index.html.spt
www/assets/gratipay.css.spt
www/index.html.spt
www/on/npm/%package/index.html.spt
www/~/%username/emails/verify.html.spt
www/~/%username/routes/credit-card.spt

Part of #4305, follows on #4410.

Clean up UX some more

---

gratipay/models/participant/__init__.py
gratipay/models/participant/email.py
tests/py/test_email.py
tests/ttw/test_package_claiming.py
www/~/%username/emails/verify.html.spt

Part of #4305, follows on #4423.
This is a sub-par experience when arriving via a package claiming workflow:

List packages on verification

---

scss/components/select.scss

Part of #4305, follows on #4428.
Turns this:
Into this:
Still falls apart on a watch. ☺️

Fix width bug

---

docs/index.rst
gratipay/utils/history.py
sql/branch.sql
tests/py/test_history.py
www/~/%username/history/export.spt
www/~/%username/history/index.html.spt

#4399 (Export as CSV yields blank file)
This is a regression from the move to Gratipay 2.0. We moved all internal money-moving logic to the `payments` table instead of `transfers`, but when history is fetched - only the `transfers` table is hit. 
This affects the yearly balances calculation, exporting `giving` and exporting `taking`. I've solved the first 2 as part of this PR (since they are actually used in the UI right now). Added a note about fixing `taking` - that can be a separate PR.

Fix export CSV bug (#4399)

---

templates/base.html
tests/py/test_notifications.py

This should take care of [update the "★ announcement ★" link](https://github.com/gratipay/gratipay.com/issues/4148#issue-184259778)
**NB:** I may need to change the actually link address if @whit537/ @aandis changes the path of the search page over time.

update the "★ announcement ★" link

---

gratipay/testing/harness.py
tests/py/test_email.py
www/~/%username/emails/modify.json.spt

Prevent claiming already-claimed packages

---

js/gratipay/packages.js
scss/components/listing.scss
scss/components/text-treatments.scss
scss/pages/package.scss
tests/py/test_www_npm_package.py
tests/ttw/test_package_claiming.py
www/on/npm/%package/index.html.spt
www/on/npm/index.html.spt
www/~/%username/emails/modify.json.spt

Add bulk claiming at /on/npm/

---

gratipay/utils/listings.py
gratipay/utils/tabs.py
scss/elements/buttons-knobs.scss
templates/nav-tabs.html
www/index.html.spt
www/search.spt

Factored out of #4507.
- listings helper for combined project/package situations
- tabs helper
- minor formatting tweaks

Refactor ahead of package.json discovery

---

bin/masspay.py
tests/py/test_dashboard.py
tests/py/test_record_an_exchange.py
www/~/%username/history/record-an-exchange.spt

As per @dmk246 suggestion [here](https://github.com/gratipay/gratipay.com/pull/3912#issuecomment-283485576) #4361 only took care of exchanges that recorded charges to participants. Masspay which is used for payouts were still recording NULL refs since there was no way to record a ref via `record_an_exchange.spt` 
This PR is to fix this issue.

Start recording ref when recording an exchange in masspay

---

js/gratipay/confirm.js
js/gratipay/countryChooser.js
js/gratipay/modal.js
scss/components/confirmation-modal.scss
scss/components/modal.scss
scss/pages/identities.scss
scss/variables.scss
tests/ttw/test_team_distributing.py
www/%team/distributing/index.html.spt
www/assets/gratipay.css.spt
www/~/%username/identities/index.spt

Preparation for https://github.com/gratipay/gratipay.com/issues/1052#issuecomment-309198597. This seems like a good enough chunk to review, hence split into a separate PR.

Extract a modal component

---

401.spt
js/gratipay.js
js/gratipay/sign-in.js
scss/components/modal.scss
scss/components/sign_in.scss
scss/mixins/icons.scss
scss/variables.scss
templates/base.html
templates/sign-in-modal.html
templates/sign-in-using.html
tests/ttw/test_package_claiming.py
tests/ttw/test_sign_in.py

Add sign-in modal

---

bin/masspay.py

Discovered in gratipay/inside.gratipay.com#1110.

Fix bug in MassPay vis-a-vis refs

---

gratipay/models/participant/email.py
tests/py/test_email.py

When the address is already verified and the user starts a package claim twice, we aren't clearing out old nonces properly.

Fix bug in package claiming when address verified

---

gratipay/security/__init__.py
tests/py/test_security.py
www/~/%username/widget.html.spt

This should resolve the worst of the CSP reports in https://github.com/gratipay/inside.gratipay.com/issues/1118.

Whitelist the widget CSS for CSP

---

gratipay/models/package/__init__.py
gratipay/models/package/team.py
tests/py/test_packages.py
tests/py/test_pages.py
tests/py/test_www_npm_package.py
tests/ttw/test_package_claiming.py
www/on/npm/%package.spt

npm has a concept of "[scoped](https://docs.npmjs.com/misc/scope)" packages with special package names of the form `@foo/bar`. We need to support these as package names under `/on/npm/` and do some smarts to use just `bar` for the project name when claiming. Closes #4496.

Add support for npm scopes

---

gratipay/testing/browser.py

#4616 &rarr;
I tried upgrading Selenium and Splinter but that didn't resolve the issue.
Discovered while working on https://github.com/gratipay/gratipay.com/pull/4613. Should be an easy merge if anyone wants it before I start self-merging per https://github.com/gratipay/gratipay.com/pull/4598#issuecomment-328309598.

Work around bug in Selenium 3.4.3 + Chrome 60

---

deploy/before.sql
gratipay/homepage.py
gratipay/models/payment_for_open_source.py
tests/py/fixtures/BadCharge.yml
tests/py/fixtures/GoodCharge.yml
tests/py/fixtures/PayForOpenSource.yml
tests/py/fixtures/TestPaymentForOpenSource.yml
tests/py/test_payments_for_open_source.py
tests/py/test_www_homepage.py

Clean up JSON endpoint for homepage form

---

gratipay/models/__init__.py
gratipay/models/participant/__init__.py
gratipay/security/authentication/__init__.py
gratipay/security/authentication/website_helpers.py
templates/sign-in-modal.html
tests/ttw/test_sign_in.py
www/auth/signup.json.spt

Part of #4539, follows #4550.
- "sign-in" is a noun, verb is "sign in"
- order of functions is per order in algorithm
- usual Python style is actually two spaces between functions
- ... and no space between docstring and first import

Tinker with comments and copy

---

js/gratipay/homepage.js

**Steps**
- User makes multiple errors when filling the homepage form
- User fixes one error, submits form
**Expected:** 
The error highlighting and text should only be shown for the field that still has an error. 
**Actual**: 
Errors are still visible on both fields.

Homepage: Clear errors on resubmission

---

deploy/before.sql
gratipay/homepage.py
gratipay/models/payment_for_open_source.py
gratipay/testing/harness.py
scss/pages/homepage.scss
tests/py/test_www_homepage.py
tests/ttw/test_homepage.py
www/browse/payments/%uuid/invoice.spt
www/index.spt

One notch better than a note to email us. I think this is important to our pitch to companies, per https://github.com/gratipay/inside.gratipay.com/issues/987#issuecomment-304707443.

Add a simple field to collect info re: projects

---

js/gratipay/packages.js
js/gratipay/select.js
scss/pages/package.scss
tests/ttw/test_package_claiming.py
www/on/npm/%package.spt
www/~/%username/emails/modify.json.spt

&larr; Limit pending verifications (#4579) — Support queueing w/o participants (#4548) &rarr;
-------------
Implement the "Ready to verify" idea from https://github.com/gratipay/gratipay.com/issues/4557#issuecomment-324469116.

"Ready to verify"

---

tests/ttw/test_homepage.py
www/index.spt

This is it, the mental shift we [need to make](https://github.com/gratipay/inside.gratipay.com/issues/1160#issuecomment-332998643) to get out of our own heads and into our customer's.
"Pay for open source" is about _our_ problems and motivations.
"Invest in open source" is about _their_ problems and motivations.

Make a big mental shift

---

scss/pages/homepage.scss
www/index.spt

We were overloading the legend instead of using a label, which got gunked up in #4664:
I've since learned we can use multiple labels for one input, so we don't need the legend hack after all.
cc: @EdOverflow @pinoaffe

Fix label regression

---

www/index.spt

We want to start building our list under https://github.com/gratipay/inside.gratipay.com/issues/1190 but don't want people to see the campaign quite yet. Will announce later this week when the list is built.
[slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1506972954000584)

Turn campaign box off until we're really ready

---

gratipay/models/team/__init__.py
www/%team/receiving/index.html.spt

From https://github.com/gratipay/gratipay.com/issues/4667#issuecomment-333806874: 
> Questions like these are hard for me to answer without speculation because I can't just query the database and giving is anonymous even for admin users.
Screenshot:

Show current payment instructions to Admins

---

scss/pages/homepage.scss

Fix #BackTheStack text on small screens
